<div class="body-img">
<img src="./img/party.jpg" alt="world">
</div>
<div class="body-content">
<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus in erat ut maximus. Donec vel ante varius, euismod risus nec, laoreet nulla. Etiam bibendum mollis massa vitae convallis. Phasellus in venenatis ipsum, consequat placerat justo. Sed sed elementum turpis, eu aliquam eros. Vivamus et feugiat diam, eu congue lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent molestie nisl at nibh ornare, sit amet facilisis tortor consectetur. Duis lobortis feugiat ex ac scelerisque. Integer ut ex ut justo faucibus tempus id et arcu. Curabitur tempor nisi non quam vulputate, vitae viverra justo accumsan. Nunc mollis mauris arcu, eget maximus purus eleifend id.

Nam arcu odio, scelerisque nec gravida vitae, efficitur in ante. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus odio felis, rhoncus vel orci quis, hendrerit congue est. Praesent tortor tellus, imperdiet tempor elementum ac, blandit nec ante. Aliquam non urna rutrum, congue ipsum eget, laoreet risus. Nam sollicitudin urna lobortis diam aliquam, in rutrum dolor hendrerit. Nam sapien augue, vulputate quis dignissim ut, elementum sed ex. Nulla fermentum in neque sollicitudin pulvinar. Fusce maximus mi ac laoreet congue. Nulla quis est bibendum, posuere ligula id, lobortis orci. Nullam nec lorem leo. Curabitur varius iaculis neque, quis volutpat ex vehicula sit amet. Phasellus sit amet luctus lorem, eu finibus purus. Nullam pharetra quam ac tincidunt condimentum. Curabitur pulvinar ultrices mattis. Curabitur quis feugiat neque.

Etiam pellentesque magna nunc, in efficitur mi sollicitudin eu. Pellentesque suscipit euismod libero, a finibus leo venenatis eu. Etiam sodales eu urna quis malesuada. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent mollis vitae libero sed tincidunt. Vestibulum quis convallis est, lacinia molestie leo. Donec convallis quam vel magna maximus, sit amet suscipit nunc tempor. Vestibulum in augue a mauris fermentum tristique. Morbi convallis nisi ut nulla sagittis, a vehicula nunc dignissim. Aliquam interdum luctus lorem, vitae euismod odio tempus eu. Nam sed pretium diam.

Praesent et vehicula lorem. Nulla eget velit in ante tincidunt bibendum. Aenean sed tincidunt diam, quis tincidunt nisi. Etiam blandit erat quis erat aliquet, id pulvinar tellus volutpat. Fusce a hendrerit nisi, eget consectetur velit. Maecenas dapibus justo tellus, ac mollis eros vulputate vulputate. Donec aliquet sapien id dui hendrerit, nec ultrices arcu sagittis. Duis venenatis suscipit volutpat. Aenean pretium condimentum nulla, ut cursus turpis interdum eget. Nullam mattis, nulla ac bibendum tempus, lacus ex laoreet eros, nec pulvinar sapien augue et magna. Aliquam eu malesuada est, nec semper dui. Praesent scelerisque lacus felis, a congue arcu rutrum vel. Nam facilisis feugiat risus, tincidunt pretium mauris venenatis at. Quisque rhoncus quam metus, ut suscipit ex tincidunt id. Donec mollis sed sapien at lobortis.

Morbi arcu felis, finibus non augue sit amet, egestas ultricies odio. Etiam tellus leo, aliquam a luctus et, scelerisque non metus. Phasellus quis tristique urna. Pellentesque a augue sit amet nibh tincidunt malesuada nec quis purus. Fusce eros velit, mattis non consectetur et, luctus in nisi. Sed ac nulla at odio varius volutpat. Donec laoreet turpis eget erat condimentum, pharetra scelerisque ex ornare. Quisque efficitur purus in elit tincidunt, in dignissim purus eleifend. 


Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus in erat ut maximus. Donec vel ante varius, euismod risus nec, laoreet nulla. Etiam bibendum mollis massa vitae convallis. Phasellus in venenatis ipsum, consequat placerat justo. Sed sed elementum turpis, eu aliquam eros. Vivamus et feugiat diam, eu congue lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent molestie nisl at nibh ornare, sit amet facilisis tortor consectetur. Duis lobortis feugiat ex ac scelerisque. Integer ut ex ut justo faucibus tempus id et arcu. Curabitur tempor nisi non quam vulputate, vitae viverra justo accumsan. Nunc mollis mauris arcu, eget maximus purus eleifend id.

Nam arcu odio, scelerisque nec gravida vitae, efficitur in ante. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus odio felis, rhoncus vel orci quis, hendrerit congue est. Praesent tortor tellus, imperdiet tempor elementum ac, blandit nec ante. Aliquam non urna rutrum, congue ipsum eget, laoreet risus. Nam sollicitudin urna lobortis diam aliquam, in rutrum dolor hendrerit. Nam sapien augue, vulputate quis dignissim ut, elementum sed ex. Nulla fermentum in neque sollicitudin pulvinar. Fusce maximus mi ac laoreet congue. Nulla quis est bibendum, posuere ligula id, lobortis orci. Nullam nec lorem leo. Curabitur varius iaculis neque, quis volutpat ex vehicula sit amet. Phasellus sit amet luctus lorem, eu finibus purus. Nullam pharetra quam ac tincidunt condimentum. Curabitur pulvinar ultrices mattis. Curabitur quis feugiat neque.

Etiam pellentesque magna nunc, in efficitur mi sollicitudin eu. Pellentesque suscipit euismod libero, a finibus leo venenatis eu. Etiam sodales eu urna quis malesuada. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent mollis vitae libero sed tincidunt. Vestibulum quis convallis est, lacinia molestie leo. Donec convallis quam vel magna maximus, sit amet suscipit nunc tempor. Vestibulum in augue a mauris fermentum tristique. Morbi convallis nisi ut nulla sagittis, a vehicula nunc dignissim. Aliquam interdum luctus lorem, vitae euismod odio tempus eu. Nam sed pretium diam.

Praesent et vehicula lorem. Nulla eget velit in ante tincidunt bibendum. Aenean sed tincidunt diam, quis tincidunt nisi. Etiam blandit erat quis erat aliquet, id pulvinar tellus volutpat. Fusce a hendrerit nisi, eget consectetur velit. Maecenas dapibus justo tellus, ac mollis eros vulputate vulputate. Donec aliquet sapien id dui hendrerit, nec ultrices arcu sagittis. Duis venenatis suscipit volutpat. Aenean pretium condimentum nulla, ut cursus turpis interdum eget. Nullam mattis, nulla ac bibendum tempus, lacus ex laoreet eros, nec pulvinar sapien augue et magna. Aliquam eu malesuada est, nec semper dui. Praesent scelerisque lacus felis, a congue arcu rutrum vel. Nam facilisis feugiat risus, tincidunt pretium mauris venenatis at. Quisque rhoncus quam metus, ut suscipit ex tincidunt id. Donec mollis sed sapien at lobortis.

Morbi arcu felis, finibus non augue sit amet, egestas ultricies odio. Etiam tellus leo, aliquam a luctus et, scelerisque non metus. Phasellus quis tristique urna. Pellentesque a augue sit amet nibh tincidunt malesuada nec quis purus. Fusce eros velit, mattis non consectetur et, luctus in nisi. Sed ac nulla at odio varius volutpat. Donec laoreet turpis eget erat condimentum, pharetra scelerisque ex ornare. Quisque efficitur purus in elit tincidunt, in dignissim purus eleifend. 
</div>