<div class="body-img">
<img src="./img/milky.jpg" alt="world">
</div>
<div class="body-content">
<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus in erat ut maximus. Donec vel ante varius, euismod risus nec, laoreet nulla. Etiam bibendum mollis massa vitae convallis. Phasellus in venenatis ipsum, consequat placerat justo. Sed sed elementum turpis, eu aliquam eros. Vivamus et feugiat diam, eu congue lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent molestie nisl at nibh ornare, sit amet facilisis tortor consectetur. Duis lobortis feugiat ex ac scelerisque. Integer ut ex ut justo faucibus tempus id et arcu. Curabitur tempor nisi non quam vulputate, vitae viverra justo accumsan. Nunc mollis mauris arcu, eget maximus purus eleifend id.

Nam arcu odio, scelerisque nec gravida vitae, efficitur in ante. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus odio felis, rhoncus vel orci quis, hendrerit congue est. Praesent tortor tellus, imperdiet tempor elementum ac, blandit nec ante. Aliquam non urna rutrum, congue ipsum eget, laoreet risus. Nam sollicitudin urna lobortis diam aliquam, in rutrum dolor hendrerit. Nam sapien augue, vulputate quis dignissim ut, elementum sed ex. Nulla fermentum in neque sollicitudin pulvinar. Fusce maximus mi ac laoreet congue. Nulla quis est bibendum, posuere ligula id, lobortis orci. Nullam nec lorem leo. Curabitur varius iaculis neque, quis volutpat ex vehicula sit amet. Phasellus sit amet luctus lorem, eu finibus purus. Nullam pharetra quam ac tincidunt condimentum. Curabitur pulvinar ultrices mattis. Curabitur quis feugiat neque.

Etiam pellentesque magna nunc, in efficitur mi sollicitudin eu. Pellentesque suscipit euismod libero, a finibus leo venenatis eu. Etiam sodales eu urna quis malesuada. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent mollis vitae libero sed tincidunt. Vestibulum quis convallis est, lacinia molestie leo. Donec convallis quam vel magna maximus, sit amet suscipit nunc tempor. Vestibulum in augue a mauris fermentum tristique. Morbi convallis nisi ut nulla sagittis, a vehicula nunc dignissim. Aliquam interdum luctus lorem, vitae euismod odio tempus eu. Nam sed pretium diam.

Praesent et vehicula lorem. Nulla eget velit in ante tincidunt bibendum. Aenean sed tincidunt diam, quis tincidunt nisi. Etiam blandit erat quis erat aliquet, id pulvinar tellus volutpat. Fusce a hendrerit nisi, eget consectetur velit. Maecenas dapibus justo tellus, ac mollis eros vulputate vulputate. Donec aliquet sapien id dui hendrerit, nec ultrices arcu sagittis. Duis venenatis suscipit volutpat. Aenean pretium condimentum nulla, ut cursus turpis interdum eget. Nullam mattis, nulla ac bibendum tempus, lacus ex laoreet eros, nec pulvinar sapien augue et magna. Aliquam eu malesuada est, nec semper dui. Praesent scelerisque lacus felis, a congue arcu rutrum vel. Nam facilisis feugiat risus, tincidunt pretium mauris venenatis at. Quisque rhoncus quam metus, ut suscipit ex tincidunt id. Donec mollis sed sapien at lobortis.

¿De dónde viene?

Al contrario del pensamiento popular, el texto de Lorem Ipsum no es simplemente texto aleatorio. Tiene sus raices en una pieza cl´sica de la literatura del Latin, que data del año 45 antes de Cristo, haciendo que este adquiera mas de 2000 años de antiguedad. Richard McClintock, un profesor de Latin de la Universidad de Hampden-Sydney en Virginia, encontró una de las palabras más oscuras de la lengua del latín, "consecteur", en un pasaje de Lorem Ipsum, y al seguir leyendo distintos textos del latín, descubrió la fuente indudable. Lorem Ipsum viene de las secciones 1.10.32 y 1.10.33 de "de Finnibus Bonorum et Malorum" (Los Extremos del Bien y El Mal) por Cicero, escrito en el año 45 antes de Cristo. Este libro es un tratado de teoría de éticas, muy popular durante el Renacimiento. La primera linea del Lorem Ipsum, "Lorem ipsum dolor sit amet..", viene de una linea en la sección 1.10.32

El trozo de texto estándar de Lorem Ipsum usado desde el año 1500 es reproducido debajo para aquellos interesados. Las secciones 1.10.32 y 1.10.33 de "de Finibus Bonorum et Malorum" por Cicero son también reproducidas en su forma original exacta, acompañadas por versiones en Inglés de la traducción realizada en 1914 por H. Rackham.
¿Dónde puedo conseguirlo? 
</div>